name: mobile_remote_terminal
description: Flutter client for TH Remote Terminal.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.12.0
  shared_preferences: ^2.3.2
  xterm: ^4.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
