// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<void> startAgent({required FrbAgentConfig config}) =>
    RustLib.instance.api.crateFrbApiStartAgent(config: config);

Future<void> stopAgent() => RustLib.instance.api.crateFrbApiStopAgent();

Future<FrbAgentStatus> agentStatus() =>
    RustLib.instance.api.crateFrbApiAgentStatus();

Future<int> openTerminal({required FrbTerminalProfile profile}) =>
    RustLib.instance.api.crateFrbApiOpenTerminal(profile: profile);

Future<void> terminalWrite({required int id, required List<int> data}) =>
    RustLib.instance.api.crateFrbApiTerminalWrite(id: id, data: data);

Future<void> terminalResize(
        {required int id,
        required int cols,
        required int rows,
        required int pixelWidth,
        required int pixelHeight}) =>
    RustLib.instance.api.crateFrbApiTerminalResize(
        id: id,
        cols: cols,
        rows: rows,
        pixelWidth: pixelWidth,
        pixelHeight: pixelHeight);

Future<Uint8List?> terminalNextOutput({required int id}) =>
    RustLib.instance.api.crateFrbApiTerminalNextOutput(id: id);

Future<void> terminalClose({required int id}) =>
    RustLib.instance.api.crateFrbApiTerminalClose(id: id);

class FrbAgentConfig {
  final String relayHost;
  final int relayPort;
  final String deviceId;
  final String token;
  final String shell;
  final bool useTls;
  final bool allowBadCertificate;

  const FrbAgentConfig({
    required this.relayHost,
    required this.relayPort,
    required this.deviceId,
    required this.token,
    required this.shell,
    required this.useTls,
    required this.allowBadCertificate,
  });

  @override
  int get hashCode =>
      relayHost.hashCode ^
      relayPort.hashCode ^
      deviceId.hashCode ^
      token.hashCode ^
      shell.hashCode ^
      useTls.hashCode ^
      allowBadCertificate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbAgentConfig &&
          runtimeType == other.runtimeType &&
          relayHost == other.relayHost &&
          relayPort == other.relayPort &&
          deviceId == other.deviceId &&
          token == other.token &&
          shell == other.shell &&
          useTls == other.useTls &&
          allowBadCertificate == other.allowBadCertificate;
}

class FrbAgentStatus {
  final String kind;
  final String? message;

  const FrbAgentStatus({
    required this.kind,
    this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbAgentStatus &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

class FrbTerminalProfile {
  final String relayHost;
  final int relayPort;
  final String deviceId;
  final String sessionId;
  final String token;
  final String username;
  final bool useTls;
  final bool allowBadCertificate;

  const FrbTerminalProfile({
    required this.relayHost,
    required this.relayPort,
    required this.deviceId,
    required this.sessionId,
    required this.token,
    required this.username,
    required this.useTls,
    required this.allowBadCertificate,
  });

  @override
  int get hashCode =>
      relayHost.hashCode ^
      relayPort.hashCode ^
      deviceId.hashCode ^
      sessionId.hashCode ^
      token.hashCode ^
      username.hashCode ^
      useTls.hashCode ^
      allowBadCertificate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbTerminalProfile &&
          runtimeType == other.runtimeType &&
          relayHost == other.relayHost &&
          relayPort == other.relayPort &&
          deviceId == other.deviceId &&
          sessionId == other.sessionId &&
          token == other.token &&
          username == other.username &&
          useTls == other.useTls &&
          allowBadCertificate == other.allowBadCertificate;
}
